</main>

<footer>
  <div class="container">
    <p>&copy; Todos os direitos reservados</p>
  </div>
</footer>
    

<!--scripts-->
<?php foreach ($scripts as $script) { ?>

<script src="<?= asset('js/' . $script) ?>"></script>

<?php } ?>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCB55nVGcJCy6JPUJZdgS9q_5wxsBwVkMw"></script>

<?php //if(in_array($url, $aceptUrls)){?>
<!--<script src="<?php //echo asset('')?>js/loadTimer.js"></script>-->
<!-- <?php // }?>-->

  </body>
</html>
