<!DOCTYPE html>
<html lang="pt-br">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title><?= $title ?> | Dev Web Completo</title>
  <meta name="author" content="Eduardo Wesley" />
  <meta name="keywords" content="sistemas web,cursos de programação,desenvolvimento web,HTML5,CSS3, design responsivo" />
  <!--Até umas 10 funciona bem-->
  <meta name="description" content="Esse site é desenvolvido pelos alunos da dankicode." />

  <!--Icon-->
  <link rel="icon" href="<?= asset('favicon.ico') ?>" type="iamge/x-icon" />
  <!--CSS-->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" />
  <link rel="stylesheet" href="<?= asset('css/style.css') ?>" />
</head>

<body class="site">