<div class="box-login">
    <h2>
      Efetue o login:
    </h2>

    <form method="POST">
      <input
        type="text"
        name="username"
        placeholder="Login"
        required
      />

      <input
        type="password"
        name="password"
        placeholder="Senha"
        required
      />

      <div class="form-group">
        <input
          type="checkbox"
          name="remember-login"
          id="remember-login"
        />

        <label for="remember-login">
          Desejo lembrar a senha.
        </label>
      </div>

      <input
        class="btn-form"
        type="submit"
        name="logar"
        value="Logar"
      />
    </form>
</div><!--box-login-->