<section class="box-content b1">
    <h2><i class="fas fa-user-edit"></i> Adicionar Depoimento</h2>

    <form method="POST" enctype="multipart/form-data">
      <?php foreach ($data->columns as $value) { ?>
        <div class="form-group">
            <label>
              <?= ucfirst($value['COLUMN_NAME']) ?>:

              <?php if ($value['COLUMN_TYPE'] === 'longtext' || $value['COLUMN_TYPE'] === 'text') { ?>
                <textarea id="name" type="text" name="<?= $value['COLUMN_NAME'] ?>"  required></textarea>
              <?php } else { ?>
                <input id="name" type="text" name="<?= $value['COLUMN_NAME'] ?>"  required />
              <?php } ?>
            </label>
        </div><!--form-group-->
      <?php } ?>

      <div class="form-group">
        <input class="btn-form" type="submit" name="acao" value="Cadastrar" />
      </div><!--form-group-->
    </form>
</section><!--box-content-->