<section class="box-content b1">
  <h2>
    <i class="fas fa-user-edit"></i> 

    Adicionar Depoimento
  </h2>

  <form
    method="POST"
    enctype="multipart/form-data"
  >
    <?php foreach ($columns as $value) { ?>
      <div class="form-group <?= $value['name'] === $img_field ? 'file' : '' ?>">
        <label>
          <?= ucfirst($value['name']) ?>:

          <?php if ($value['type'] === 'longtext' || $value['type'] === 'text') { ?>
            <textarea
              class="form-field"
              id="name"
              type="text"
              name="<?= $value['name'] ?>"
              required
            ></textarea>
          <?php } else if (isset($img_field) && $value['name'] === $img_field) { ?>
            <label class="fake-file">
              Upload

              <input
                class="form-field"
                type="file"
                accept="image/*"
                name="<?= $value['name'] ?>"
              />
            </label>
          <?php } else { ?>
            <input
              class="form-field"
              id="name"
              type="text"
              name="<?= $value['name'] ?>"
              required
            />
          <?php } ?>
        </label>
      </div>
    <?php } ?>

    <div class="form-group">
      <button
        class="btn-form"
        type="submit"
      >
        Cadastrar
      </button>
    </div>
  </form>
</section>
