<section class="box-content b1">
  <h2>
    <i class="fas fa-user-edit"></i>

    Editar Depoimento
  </h2>

  <form method="POST" enctype="multipart/form-data">
    <?php foreach ($columns as $value) { ?>
      <div class="form-group <?= $value['name'] === $img_field ? 'file' : '' ?>">
        <label>
          <?= ucfirst($value['name']) ?>:

          <?php if ($value['type'] === 'longtext' || $value['type'] === 'text') { ?>
            <textarea
              id="name"
              type="text"
              name="<?= $value['name'] ?>"
              required
            >
              <?= $item[$value['name']] ?>
            </textarea>
          <?php } else if (isset($img_field) && $value['name'] === $img_field) { ?>
            <label class="fake-file">Upload
              <input
                type="file"
                accept="image/*"
                name="<?= $value['name'] ?>" 
              />
            </label>
          <?php } else { ?>
            <input
              id="name"
              type="text"
              name="<?= $value['name'] ?>"
              value="<?= $item[$value['name']] ?>"
              required
            />
          <?php } ?>
        </label>
      </div>
      <!--form-group-->
    <?php } ?>

    <div class="form-group">
      <button class="btn-form" type="submit">
        Atualizar
      </button>
    </div>
    <!--form-group-->
  </form>
</section>
<!--box-content-->