      </main>
    </div>
</div>

<script src="<?= PATH;?>js/jquery-3.4.1.min.js"></script>
<script src="<?= PATH;?>js/jquery.mask.js"></script>
<script src="<?= INCLUDE_PATH_PANEL;?>js/main.js"></script>
<script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
<script src="<?= INCLUDE_PATH_PANEL;?>js/jquery.form.min.js"></script>
<script src="<?= INCLUDE_PATH_PANEL;?>js/helperMask.js"></script>
<script src="<?= INCLUDE_PATH_PANEL;?>js/ajax.js"></script>

<?php

// Painel::loadJS(['clients.js'], 'list-clients',);

?>

<script>
    tinymce.init({
        selector: '.tinymce',
        plugins: 'image',
        height: 300,
        menubar: 'insert'
    });
</script>