<section class="contato">
  <div id="map"></div>

  <div class="container">
    <form
      method="POST"
      class="ajax-form"
    >
      <input
        class="form-field"
        type="text"
        name="name"
        placeholder="Nome"
        required
      />

      <input
        class="form-field"
        type="email"
        name="email"
        placeholder="E-mail"
        required
      />

      <input
        class="form-field"
        type="text"
        name="telefone"
        placeholder="Telefone"
        required
      />

      <textarea
        class="form-field"
        name="messagem"
        placeholder="Sua menssgem"
        required
      ></textarea>

      <button
        type="submit"
        class="btn"
      >
        Enviar
      </button>
    </form>
  </div>
</section>