<section class="banner-main">
        <div class="overlay"></div>

        <div class="slider">
            <?php
                foreach($data->slides as $value){
            ?>
                <!--title e alt otimizao para SEO-->
                <div class="slide-img" style="background-image: url('<?= asset('images/uploads/'. $value['slide']) ?>');"></div>
            <?php }?>
            <div class="bullets"></div>
        </div>

        <div class="container flex center">
            <form method="POST" class="ajax-form">
                <h2>Qual o seu melhor e-mail?</h2>
                <input type="email" name="email" required />
                <input type="submit" name="acao" value="Cadastrar" />
            </form>
        </div>
    </section><!--banner-main-->

    <section id="about" class="descricao-author">
        <div class="container flex space">
            <div class="c2">
                <h2><?= $data->name_author ?></h2>
                <p><?= $data->description ?></p>
            </div>

            <div class="c2">
                <img src="<?= asset('images/pp.jpg') ?>" />
            </div>
        </div>
    </section><!--descricao-author-->

    <section id="services" class="especialiades">
        <div class="container">
            <h2 class="title">Especialidade</h2>
            <div class="content flex">
                <div class="box-especialidade c3">
                    <h2><i class="<?= $data->icone_1 ?>"></i></h2>
                    <h3>CSS3</h3>
                    <p>
                        <?= $data->descricao_1 ?>
                    </p>
                </div><!--box-especialidade-->

                <div class="box-especialidade c3">
                    <h2><i class="<?= $data->icone_2 ?>"></i></h2>
                    <h3>HTML5</h3>
                    <p>
                        <?= $data->descricao_2 ?>
                    </p>
                </div><!--box-especialidade-->

                <div class="box-especialidade c3">
                    <h2><i class="<?= $data->icone_3 ?>"></i></h2>
                    <h3>Javascript</h3>
                    <p>
                        <?= $data->descricao_3 ?>
                    </p>
                </div><!--box-especialidade-->
            </div><!--content-->
        </div><!--container-->
    </section><!--especialidades-->

<section class="extras">
<div class="container">
    <div class="depoimentos flex">
        <div class="c2">
            <h2 class="title">Depoimentos dos nossos clientes</h2>

            <?php foreach ($data->depoimentos as $value) { ?>
            <div class="depoimento-single">
                <p>
                " <?php echo $value['depoimento'];?> "
                </p>
                <p class="author"><?php echo $value['name']; ?> - <?php echo $value['date'];?></p>
            </div>
            <?php }?>
        </div>

        <div class="c2">
            <h2 class="title">Serviços</h2>
            <ul>
                <?php foreach ($data->services as $value) { ?>
                    <li><?php echo $value['servico']; ?></li>
                <?php }?>
            </ul>
        </div>
    </div><!--flex-depoimentos-->
</div><!--container-->

</section><!--extras-->