<section class="header-noticias">
  <div class="container">
    <h2>
      <i class="far fa-bell"></i>
    </h2>

    <h2>
      Aconpanhe as ultimas <b>noticias do portal</b>
    </h2>
  </div>
</section>

<section class="container-portal">
  <div class="container">
    <aside>
      <div class="box-content-sidebar">
        <h3>
          <i class="fas fa-search"></i> Realizar uma busca:
        </h3>

        <form method="GET">
          <input
            class="form-field"
            type="text"
            name="parametro"
            placeholder="O que deseja procurar?"
            required
          />

          <button type="submit">
            pesquisar
          </button>
        </form>
      </div>

      <div class="box-content-sidebar">
        <h3>
          <i class="fas fa-list-ul"></i> Selecione a categoria:
        </h3>

        <form>
          <select
            class="form-field"
            name="categoria"
          >
            <option value="" selected>
              Todas as categorias
            </option>

            <?php foreach ($categorias as $value) { ?>
              <option <?= strpos($base_url, $value['slug']) ? 'selected' : '' ?> value="<?= $value['slug'] ?>">
                <?= ucfirst($value['name']) ?>
              </option>
            <?php } ?>
          </select>
        </form>
      </div>

      <div class="box-content-sidebar">
        <h3>
          <i class="fas fa-user"></i> Sobre o autor:
        </h3>

        <div class="autor-box-portal">
          <img
            src="<?= asset('images/pp.jpg') ?>"
            alt="author"
          />

          <div class="text-autor-portal">
            <h3>
              <?= $info_author['name_author'] ?>
            </h3>

            <p>
              <?php
                echo substr($info_author['descricao'], 0, 500);
                echo strlen($info_author['descricao']) >= 500 ? '...' : '';
              ?>
            </p>
          </div>
        </div>
      </div>
    </aside>

    <main>
      <div class="header-content-portal">
        <?php
        if (!isset($search)) {
          if (!$categoria) {
            echo "<h2>Vizualizando todas as noticias</h2>";
          } else {
            echo "<h2>Vizualizando noticias em <span>$categoria[name]</span></h2>";
          }
        } else
          echo "<h2>Vizualizando resultado da busca por <span>$_POST[parametro]</span></h2>";
        ?>
      </div>

      <?php
      if (count($noticias)) {
        foreach ($noticias as $value) {
      ?>

          <div class="box-single-content">
            <h2>
              <?= date('d-m-Y', strtotime($value['date'])) . " - $value[title]" ?>
            </h2>

            <p>
              <?= substr(strip_tags($value['conteudo']), 0, 500) . '...' ?>
            </p>

            <a href="<?= route('/') ?>news/<?= $value['category']['name'] . "/$value[slug]" ?>">
              Leia Mais
            </a>
          </div>

      <?php
          }
        } else {
          echo "Nenhuma noticia encontrada :(";
        }
      ?>

      <!-- <div class="paginacao">
            <?php
            // for($i = 1; $i <= $totalPaginas; $i++){
            //     if($i == $pagina)
            //         echo '<a class="active" href="'.INCLUDE_PATH.'news/'.$categoria['slug'].'?pag='.$i.'">'.$i.'</a>';
            //     else
            //         echo '<a href="'.INCLUDE_PATH.'news/'.$categoria['slug'].'?pag='.$i.'">'.$i.'</a>';
            // }
            ?>
        </div> -->
    </main>
  </div>
</section>
